Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\guozhengping\AppData\Local\uv\cache\archive-v0\R54QjRivZjeQEB6RXzxTZ\Scripts\mcp-server-git.exe\__main__.py", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\guozhengping\AppData\Local\uv\cache\archive-v0\R54QjRivZjeQEB6RXzxTZ\Lib\site-packages\click\core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\guozhengping\AppData\Local\uv\cache\archive-v0\R54QjRivZjeQEB6RXzxTZ\Lib\site-packages\click\core.py", line 1363, in main
    rv = self.invoke(ctx)
  File "C:\Users\guozhengping\AppData\Local\uv\cache\archive-v0\R54QjRivZjeQEB6RXzxTZ\Lib\site-packages\click\core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guozhengping\AppData\Local\uv\cache\archive-v0\R54QjRivZjeQEB6RXzxTZ\Lib\site-packages\click\core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\guozhengping\AppData\Local\uv\cache\archive-v0\R54QjRivZjeQEB6RXzxTZ\Lib\site-packages\mcp_server_git\__init__.py", line 21, in main
    asyncio.run(serve(repository))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\LQ\soft\Python313\Lib\asyncio\runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "D:\LQ\soft\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\LQ\soft\Python313\Lib\asyncio\base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\guozhengping\AppData\Local\uv\cache\archive-v0\R54QjRivZjeQEB6RXzxTZ\Lib\site-packages\mcp_server_git\server.py", line 208, in serve
    git.Repo(repository)
    ~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\guozhengping\AppData\Local\uv\cache\archive-v0\R54QjRivZjeQEB6RXzxTZ\Lib\site-packages\git\repo\base.py", line 236, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: C:\Users\guozhengping\path\to\git\repo